
section .vesa_info

; this 512 byte long structure holds information about the structure
global vesa_info_block
vesa_info_block:
	.signature:		  dd "VBE2"
	.vbe_version:   dd 0
  .oem_base:      dw 0
  .oem_offset:    dw 0
  .capabilities:  dd 0
  .modes_base:    dw 0
  .modes_offset:  dw 0
  .video_memory:  dw 0
  .software_rev:  dw 0
  .vendor_base:   dw 0
  .vendor_off:    dw 0
  .product_name_base: dw 0
  .product_name_off:  dw 0
  .product_rev_base:  dw 0
  .product_rev_off:   dw 0
  .reserved:      resb 478

global vesa_mode_info

; this structure holds the information generated by calling one of the vesamodes provided
; by the modes array(located @ [modes_base] + [modes_offset])
; this will be referenced by the kernel with an (extern vesa_mode_info_t vesa_mode_info)

vesa_mode_info:
  
